# Generated by Django 3.2.21 on 2023-09-21 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True)),
                ('party_size', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=2)),
                ('availability', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('booking_date', models.DateField()),
                ('booking_time', models.IntegerField(choices=[(1, '11:00 - 12:00'), (2, '12:00 - 13:00'), (3, '13:00 - 14:00'), (4, '14:00 - 15:00'), (5, '15:00 - 16:00'), (6, '16:00 - 17:00'), (7, '17:00 - 18:00'), (8, '18:00 - 19:00'), (9, '19:00 - 20:00'), (10, '20:00 - 21:00'), (11, '21:00 - 22:00')], default=1)),
                ('timestamp_booking_made', models.DateTimeField(auto_now=True)),
                ('booking_notes', models.CharField(max_length=1000, null=True)),
                ('booking_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='bookings.table')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booking_date', 'booking_time'],
            },
        ),
    ]
