# Generated by Django 3.2.21 on 2023-09-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='party_size_for_booking',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.IntegerField(choices=[(1, '09:00 - 10:00'), (2, '10:00 - 11:00'), (3, '11:00 - 12:00'), (4, '12:00 - 13:00'), (5, '13:00 - 14:00'), (6, '14:00 - 15:00'), (7, '15:00 - 16:00'), (8, '16:00 - 17:00'), (9, '17:00 - 18:00')], default=1),
        ),
    ]
